# Gausian Naive Bayes

 - Informações sobre o conjunto de dados
    1. variance of Wavelet Transformed image (continuous)
    2. skewness of Wavelet Transformed image (continuous)
    3. curtosis of Wavelet Transformed image (continuous)
    4. entropy of image (continuous)
    5. class (integer)





In [44]:
import sys 

sys.path.append("/home/davi/PycharmProjects/Reconhecimento-de-Padroes")


from numpy import zeros, concatenate, array, where, log, argmax, inf, sqrt, pi, exp, mean, ndarray
from Strings import string
from sklearn.model_selection import train_test_split
from numpy.random import rand
from src.Utils.utils import sigmoid, get_data, get_confusion_matrix, plot_confusion_matrix
from sklearn.model_selection import KFold


In [45]:
def gaussian(x_i, variance_i_c, mean_i_c):
    Fraction = (1. / sqrt(2 * pi * variance_i_c))
    Exponential = (-1. / 2.) * ((x_i - mean_i_c) / sqrt(variance_i_c)) ** 2

    return Fraction * exp(Exponential)

In [46]:
def predict(p):
    return argmax(p)


In [47]:
def train(x_train, y_train):
    if isinstance(max(y_train), ndarray):
        max_class = max(y_train)[0]
    else:
        max_class = max(y_train)
    N_class = max_class + 1
    N_examples = x_train.shape[0]
    thetas_c = zeros((int(N_class), 1))

    for c in y_train:
        if isinstance(c, ndarray):
            indice = c[0]
        else:
            indice = c
        thetas_c[int(indice)] += 1

    thetas_c = thetas_c / N_examples

    matrix_mean = zeros((x_train.shape[1], int(N_class))).T
    variance_matrix = zeros((x_train.shape[1], int(N_class))).T

    for c in range(int(N_class)):
        N_y = len(where(y_train == c)[0])
        for i in range(x_train.shape[1]):
            indices = where(y_train == c)[0]
            matrix_mean[c][i] = (1. / (1. * N_y)) * sum(x_train[:, i][indices])
            variance_matrix[c][i] = (1. / (1. * N_y)) * sum((x_train[:, i][indices] - matrix_mean[c][i]) ** 2)

    return matrix_mean, variance_matrix, thetas_c


In [48]:
def test(x_test, y_test, matrix_mean, variance_matrix, thetas_c, flag=False):
    cont = 0

    for j in range(x_test.shape[0]):
        x_example = x_test[j]
        y_example = y_test[j]

        P_yx = zeros((matrix_mean.shape[0], 1))

        for c in range(matrix_mean.shape[0]):
            p_y = log(thetas_c[c])
            for i in range(matrix_mean.shape[1]):
                X_i = x_example[i]
                P_yx[c] += log(gaussian(X_i, variance_matrix[c][i], matrix_mean[c][i]))
            P_yx[c] += p_y

        Y = predict(P_yx)
        if flag:
            return Y
        
        if Y == y_example:
            cont += 1

    return cont / (1.0 * j)


In [49]:

data = get_data("data_banknote_authentication.txt", type="csv")
number_lines = data.shape[0]
number_columns = data.shape[1]
X = array(data, ndmin=2)[:, :number_columns-1]
Y =   array(array(data, ndmin=2)[:, number_columns-1], ndmin=2).T
train_size = .8
test_size = .2

indices = where(Y == -1)
Y[indices] = 0

print(X)
print(Y) 

[[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]
[[0.]
 [0.]
 [0.]
 ...
 [1.]
 [1.]
 [1.]]


In [50]:
acc = []
acc_eta = []
kf = KFold(n_splits=10)
eta_validation_vector = [1., 0.15, 0.1, 1e-2, 1e-3]
for realization in range(5):
    x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=test_size)
    
    # for eta_val in eta_validation_vector:
    #     acc_validation = []
    #     for train_index, test_index in kf.split(x_train):
    #         # print("TRAIN:", train_index, "TEST:", test_index)
    #         x_train_val, x_test_val = x_train[train_index], x_train[test_index]
    #         y_train_val, y_test_val = y_train[train_index], y_train[test_index]
    # 
    #         wheiths_val = train(x_train_val, y_train_val)
    #         accuracy = test(wheiths_val, x_test_val, y_test_val)
    #         
    #         acc_validation.append(accuracy)
    #     acc_eta.append(mean(acc_validation))
    #         
    #         
    # indice = argmax(acc_eta)
                
    matrix_Mean, variance_Matrix, thetas_c = train(x_train, y_train)
    accuracy = test(x_test, y_test, matrix_Mean, variance_Matrix, thetas_c)
    y_output = test(x_test, y_test, matrix_Mean, variance_Matrix, thetas_c, flag=True)
    acc.append(accuracy)
    
    
    # confusion_matrix = get_confusion_matrix(y_output, y_test)
    print(string.RUN.format(realization, 1000, accuracy, None))

# plot_confusion_matrix(confusion_matrix)    
# print(mean(acc))





            Realização: 0 

            Epocas: 1000 

            Acuracia: 0.8211678832116789 

            Matriz de confusão: None

    
          

            Realização: 1 

            Epocas: 1000 

            Acuracia: 0.8175182481751825 

            Matriz de confusão: None

    
          

            Realização: 2 

            Epocas: 1000 

            Acuracia: 0.8868613138686131 

            Matriz de confusão: None

    
          

            Realização: 3 

            Epocas: 1000 

            Acuracia: 0.8540145985401459 

            Matriz de confusão: None

    
          

            Realização: 4 

            Epocas: 1000 

            Acuracia: 0.8613138686131386 

            Matriz de confusão: None

    
          
